export enum EventTypes {
    FILE_PUBLISHED = "file.published",
    SOURCE_ISSUE_CREATED = "sourceIssue.created",
    SOURCE_ISSUE_UPDATED = "sourceIssue.updated",
    SOURCE_ISSUE_DELETED = "sourceIssue.deleted",
    SOURCE_ISSUE_COMMENT_CREATED = "sourceIssue.comment.created",
    SOURCE_ISSUE_COMMENT_UPDATED = "sourceIssue.comment.updated",
    SOURCE_ISSUE_COMMENT_DELETED = "sourceIssue.comment.deleted",
    TRANSLATION_ISSUE_CREATED = "translationIssue.created",
    TRANSLATION_ISSUE_UPDATED = "translationIssue.updated",
    TRANSLATION_ISSUE_DELETED = "translationIssue.deleted",
    TRANSLATION_ISSUE_COMMENT_CREATED = "translationIssue.comment.created",
    TRANSLATION_ISSUE_COMMENT_UPDATED = "translationIssue.comment.updated",
    TRANSLATION_ISSUE_COMMENT_DELETED = "translationIssue.comment.deleted",
    TRANSLATION_JOB_CREATED = "translationJob.created",
    TRANSLATION_JOB_UPDATED = "translationJob.updated",
    TRANSLATION_JOB_COMPLETED = "translationJob.completed",
    TRANSLATION_JOB_CANCELED = "translationJob.canceled",
    INTEGRATIONS_PLATFORM_ASSET_EXPORTED = "integrations.platform.asset.exported"
}
